# Codecov configuration
# See https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 70%

  precision: 2
  round: down
  range: 70...100

ignore:
  - "tests/"
  - "alembic/"
  - "scripts/"
  - "docs/"
  - "*.spec"
  - "setup.py"
  - "**/test_*.py"
  - "**/*_test.py"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - core/
      - infrastructure/
    carryforward: true
