"""Add supplier and purchase order tables

Revision ID: 604cd277c575
Revises: 50142a3c2287
Create Date: 2025-04-13 10:32:22.639211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604cd277c575'
down_revision: Union[str, None] = '50142a3c2287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_ordered', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('quantity_received', sa.Float(), nullable=False))
        batch_op.alter_column('product_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('product_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('cost_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_column('quantity')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_person', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('contact_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('notes')
        batch_op.drop_column('contact_person')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('supplier_name')

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.alter_column('cost_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('product_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('product_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('quantity_received')
        batch_op.drop_column('quantity_ordered')

    # ### end Alembic commands ###
