"""Add users table and link user_id to sales, movements, payments

Revision ID: 90fd479c411f
Revises: 604cd277c575
Create Date: 2025-04-13 10:46:34.238707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fd479c411f'
down_revision: Union[str, None] = '604cd277c575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip creating users table and indexes as it might already exist from previous failed attempt
    # op.create_table('users',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(), nullable=False),
    # sa.Column('password_hash', sa.String(), nullable=False),
    # sa.Column('is_active', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # Apply changes to other tables
    with op.batch_alter_table('credit_payments', schema=None) as batch_op:
        # Ensure user_id column exists before adding FK (optional, but safer)
        # batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True)) # Assuming it was added previously or exists
        batch_op.create_foreign_key(batch_op.f('fk_credit_payments_users_user_id'), 'users', ['user_id'], ['id']) # Added constraint name

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_inventory_movements_users_user_id'), 'users', ['user_id'], ['id']) # Added constraint name

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_type', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_payment_type'), ['payment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sales_users_user_id'), 'users', ['user_id'], ['id']) # Added constraint name

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_users_user_id'), type_='foreignkey') # Added constraint name
        batch_op.drop_index(batch_op.f('ix_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_payment_type'))
        batch_op.drop_column('payment_type')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_movements_users_user_id'), type_='foreignkey') # Added constraint name
        batch_op.drop_index(batch_op.f('ix_inventory_movements_user_id'))

    with op.batch_alter_table('credit_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_credit_payments_users_user_id'), type_='foreignkey') # Added constraint name

    # Skip dropping users table indexes if they weren't created reliably
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_users_username'))
    #     batch_op.drop_index(batch_op.f('ix_users_id'))

    # Skip dropping users table if it wasn't created reliably by this migration's upgrade
    # op.drop_table('users')
    # ### end Alembic commands ###
