"""Add users table and link user_id to sales, movements, payments

Revision ID: 90fd479c411f
Revises: 604cd277c575
Create Date: 2025-04-13 10:46:34.238707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fd479c411f'
down_revision: Union[str, None] = '604cd277c575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table if it doesn't exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'users' not in inspector.get_table_names():
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # Apply changes to other tables - check if tables exist before altering
    if 'credit_payments' in inspector.get_table_names():
        # Check if constraint already exists
        credit_payment_constraints = [constraint['name'] for constraint in inspector.get_foreign_keys('credit_payments')]
        with op.batch_alter_table('credit_payments', schema=None) as batch_op:
            # Only add constraint if it doesn't exist and user_id column exists
            has_user_id = 'user_id' in [col['name'] for col in inspector.get_columns('credit_payments')]
            fk_name = batch_op.f('fk_credit_payments_users_user_id')
            if has_user_id and fk_name not in credit_payment_constraints:
                batch_op.create_foreign_key(fk_name, 'users', ['user_id'], ['id'])

    if 'inventory_movements' in inspector.get_table_names():
        # Check if columns and constraints already exist
        inventory_columns = [col['name'] for col in inspector.get_columns('inventory_movements')]
        inventory_indexes = [idx['name'] for idx in inspector.get_indexes('inventory_movements')]
        inventory_constraints = [constraint['name'] for constraint in inspector.get_foreign_keys('inventory_movements')]
        
        with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
            # Add index if user_id column exists but index doesn't
            idx_name = batch_op.f('ix_inventory_movements_user_id')
            fk_name = batch_op.f('fk_inventory_movements_users_user_id')
            if 'user_id' in inventory_columns and idx_name not in inventory_indexes:
                batch_op.create_index(idx_name, ['user_id'], unique=False)
            # Add constraint if it doesn't exist
            if 'user_id' in inventory_columns and fk_name not in inventory_constraints:
                batch_op.create_foreign_key(fk_name, 'users', ['user_id'], ['id'])

    if 'sales' in inspector.get_table_names():
        # Check if columns already exist
        sales_columns = [col['name'] for col in inspector.get_columns('sales')]
        sales_indexes = [idx['name'] for idx in inspector.get_indexes('sales')]
        sales_constraints = [constraint['name'] for constraint in inspector.get_foreign_keys('sales')]
        
        with op.batch_alter_table('sales', schema=None) as batch_op:
            # Add columns if they don't exist
            if 'user_id' not in sales_columns:
                batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
            if 'payment_type' not in sales_columns:
                batch_op.add_column(sa.Column('payment_type', sa.String(), nullable=True))
                
            # Add indexes if they don't exist
            idx_payment = batch_op.f('ix_sales_payment_type')
            idx_user = batch_op.f('ix_sales_user_id')
            if 'payment_type' in sales_columns and idx_payment not in sales_indexes:
                batch_op.create_index(idx_payment, ['payment_type'], unique=False)
            if 'user_id' in sales_columns and idx_user not in sales_indexes:
                batch_op.create_index(idx_user, ['user_id'], unique=False)
                
            # Add constraint if it doesn't exist
            fk_name = batch_op.f('fk_sales_users_user_id')
            if 'user_id' in sales_columns and fk_name not in sales_constraints:
                batch_op.create_foreign_key(fk_name, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sales_users_user_id'), type_='foreignkey') # Added constraint name
        batch_op.drop_index(batch_op.f('ix_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_payment_type'))
        batch_op.drop_column('payment_type')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventory_movements_users_user_id'), type_='foreignkey') # Added constraint name
        batch_op.drop_index(batch_op.f('ix_inventory_movements_user_id'))

    with op.batch_alter_table('credit_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_credit_payments_users_user_id'), type_='foreignkey') # Added constraint name

    # Only drop users table and indexes if they were created by this migration
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'users' in inspector.get_table_names():
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_users_username'))
            batch_op.drop_index(batch_op.f('ix_users_id'))
        op.drop_table('users')
    # ### end Alembic commands ###
