"""Add customer table (Defensive attempt)

Revision ID: b1a2c3d4e5f6
Revises: 954dc49f1db3
Create Date: 2023-10-27 10:00:00.000000 # Placeholder date

"""
from typing import Sequence, Union
import logging

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Numeric
# Import custom GUID type if used in the model (adjust path if necessary)
# from infrastructure.persistence.sqlite.models_mapping import GUID

# Get the logger
log = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision: str = 'b1a2c3d4e5f6'
down_revision: Union[str, None] = '954dc49f1db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Try to create the table
    try:
        op.create_table('customers',
            sa.Column('id', sa.String(36), nullable=False),
            sa.Column('name', sa.String(), nullable=False),
            sa.Column('phone', sa.String(), nullable=True),
            sa.Column('email', sa.String(), nullable=True),
            sa.Column('address', sa.String(), nullable=True),
            sa.Column('cuit', sa.String(), nullable=True),
            sa.Column('iva_condition', sa.String(), nullable=True),
            sa.Column('credit_limit', Numeric(12, 2), nullable=False, server_default=sa.text("'0.00'")),
            sa.Column('credit_balance', Numeric(12, 2), nullable=False, server_default=sa.text("'0.00'")),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('cuit')
        )
        log.info("Successfully created 'customers' table.")
    except Exception as e:
        # If creation fails, assume it might exist from a previous failed attempt.
        log.warning(f"Could not create 'customers' table, assuming it exists: {e}")

    # Step 2: Create indexes (use batch mode for SQLite compatibility)
    # If the table already existed and had indexes, these might raise errors,
    # but are generally safer than failing on non-existent drops.
    with op.batch_alter_table('customers', schema=None) as batch_op:
        log.info("Attempting to create indexes for customers table...")
        try:
            batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
            batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
            batch_op.create_index(batch_op.f('ix_customers_cuit'), ['cuit'], unique=True)
            batch_op.create_index(batch_op.f('ix_customers_is_active'), ['is_active'], unique=False)
            log.info("Finished creating indexes for customers table.")
        except Exception as e:
            log.warning(f"Could not create indexes for 'customers' table (might already exist): {e}")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Using batch mode for downgrade as well for SQLite compatibility
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_is_active'))
        batch_op.drop_index(batch_op.f('ix_customers_cuit'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))

    op.drop_table('customers')
    # ### end Alembic commands ### 