"""Add product and department tables

Revision ID: b37e887fea79
Revises: 5704d285823f
Create Date: 2025-04-13 08:40:54.055512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37e887fea79'
down_revision: Union[str, None] = '5704d285823f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - manually added ###
    op.create_table('departments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='uq_department_name') # Added unique constraint
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)

    op.create_table('products',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('cost_price', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('sell_price', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('wholesale_price', sa.Float(), nullable=True),
        sa.Column('special_price', sa.Float(), nullable=True),
        sa.Column('department_id', sa.Integer(), nullable=True),
        sa.Column('unit', sa.String(), nullable=False, server_default='Unidad'),
        sa.Column('uses_inventory', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('quantity_in_stock', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('min_stock', sa.Float(), nullable=True, server_default='0.0'),
        sa.Column('max_stock', sa.Float(), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code', name='uq_product_code')
    )
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_department_id'), 'products', ['department_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - manually added ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_department_id'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
