"""Add customer credit fields to Sale and add CreditPayment table

Revision ID: c299e07fe555
Revises: b1a2c3d4e5f6
Create Date: 2025-04-13 09:52:19.931502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c299e07fe555'
down_revision: Union[str, None] = 'b1a2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_payments_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_payments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_credit_sale', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.create_index(batch_op.f('ix_sales_customer_id'), ['customer_id'], unique=False)
        batch_op.create_foreign_key('fk_sales_customer_id', 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_customer_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_customer_id'))
        batch_op.drop_column('is_credit_sale')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('credit_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_payments_timestamp'))
        batch_op.drop_index(batch_op.f('ix_credit_payments_id'))
        batch_op.drop_index(batch_op.f('ix_credit_payments_customer_id'))

    op.drop_table('credit_payments')
    # ### end Alembic commands ###
