from typing import Optional, Dict, Any
from pydantic import BaseModel, Field, ConfigDict

class ProblemDetail(BaseModel):
    """
    RFC 7807 Problem Details for HTTP APIs.
    https://tools.ietf.org/html/rfc7807
    """
    type: str = Field(default="about:blank", description="A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type.")
    title: Optional[str] = Field(default=None, description="A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.")
    status: Optional[int] = Field(default=None, description="The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.")
    detail: Optional[str] = Field(default=None, description="A human-readable explanation specific to this occurrence of the problem.")
    instance: Optional[str] = Field(default=None, description="A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.")
    
    # Extension members (additional properties)
    # Pydantic models handle extra fields by default if not strictly controlled by Config.extra = 'forbid'
    # For explicit definition of common extensions:
    # errors: Optional[Dict[str, Any]] = Field(default=None, description="A dictionary of validation errors or other specific error details.")

    model_config = ConfigDict(
        from_attributes=True,
        populate_by_name=True  # Allow camelCase or snake_case input if aliases are used
    )